### ISSUE TITLE
Server doesn't shutdown properly

### ISSUE THREAD

**Issue by LolHens** [JetBrains/teamcity-docker-server#13] opened 2017-07-03 07:33 UTC
When I stop the container, the webserver doesn't seem to get the exit signal and is simply killed.
This is especially a problem when using the TeamCity Commit Hooks plugin because it saves its commit hooks only on server exit which never happens.

It can be prevented by simply using tini as an entrypoint:
[https://github.com/krallin/tini](https://github.com/krallin/tini)

I tried this and it works perfectly:
[https://github.com/LolHens/docker-teamcity-server/blob/master/Dockerfile](https://github.com/LolHens/docker-teamcity-server/blob/master/Dockerfile)

I could submit a pull request if this change is wanted.

**Comment by varsy** [comment] 2017-07-04 12:33
Hello,
thank you for your solution.

We've been working on this and will come back with the answer.

Right now we're handling the start/stop actions in the following manner:
Start:  
```
docker run jetbrains/teamcity-server /opt/teamcity/bin/teamcity-server.sh run
```

Stop:
```
docker exec <teamcity-server> /opt/teamcity/bin/teamcity-server.sh stop 60
```

We're using a systemd service for that.

**Comment by VladRassokhin** [comment] 2017-07-05 15:12
Well, I cannot reproduce this problem with latest docker image.

As you can see there's trap set in 'run-server.sh' which calls 'teamcity-server.sh stop'. There may be a problem if server is unable to stop within default stop timeout (5 seconds)

**Comment by pavelsher** [comment] 2017-10-05 10:15
Should be fixed by now.

**Closed by pavelsher** 2017-10-05 10:15 UTC
